server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: MyImageLogServer
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

app:
  upload:
    base-dir: uploads
    public-url-base: http://localhost:8080/files
